/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountlyDropzone: typeof import('./components/finance/AccountlyDropzone.vue')['default']
    ContactForm: typeof import('./components/public/ContactForm.vue')['default']
    FeatureCard: typeof import('./components/public/FeatureCard.vue')['default']
    HeroSection: typeof import('./components/public/HeroSection.vue')['default']
    OmnichannelChannels: typeof import('./components/marketing/OmnichannelChannels.vue')['default']
    PricingCard: typeof import('./components/public/PricingCard.vue')['default']
    PublicFooter: typeof import('./components/public/PublicFooter.vue')['default']
    PublicHeader: typeof import('./components/public/PublicHeader.vue')['default']
    QuizQuestion: typeof import('./components/courses/QuizQuestion.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubscriptionLock: typeof import('./components/marketing/SubscriptionLock.vue')['default']
    TenantaWidget: typeof import('./components/widget/TenantaWidget.vue')['default']
    TestimonialCard: typeof import('./components/public/TestimonialCard.vue')['default']
    TestTimer: typeof import('./components/courses/TestTimer.vue')['default']
    TimerWidget: typeof import('./components/TimerWidget.vue')['default']
    WidgetChat: typeof import('./components/widget/WidgetChat.vue')['default']
    WidgetForm: typeof import('./components/widget/WidgetForm.vue')['default']
  }
}
